
package com.amberfin.ws.dark._2014._07.transcode;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.amberfin.schema.transcoderparameters.Transcodeparameters;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TranscodeWS", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
@XmlSeeAlso({
    com.amberfin.schema.transcoderparameters.ObjectFactory.class,
    com.amberfin.ws.dark._2014._07.transcode.ObjectFactory.class
})
public interface TranscodeWS {


    /**
     * 
     * @param uuid
     * @return
     *     returns com.amberfin.ws.dark._2014._07.transcode.JobEvents
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @WebResult(name = "events", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
    @RequestWrapper(localName = "getJobEvents", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobEvents")
    @ResponseWrapper(localName = "getJobEventsResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobEventsResponse")
    public JobEvents getJobEvents(
        @WebParam(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        String uuid)
        throws TranscodeWSException_Exception
    ;

    /**
     * 
     * @param uuid
     * @throws TranscodeWSNotFoundException_Exception
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelJob", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.CancelJob")
    @ResponseWrapper(localName = "cancelJobResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.CancelJobResponse")
    public void cancelJob(
        @WebParam(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        String uuid)
        throws TranscodeWSException_Exception, TranscodeWSNotFoundException_Exception
    ;

    /**
     * 
     * @param priority
     * @param uuid
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "setJobPriority", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.SetJobPriority")
    @ResponseWrapper(localName = "setJobPriorityResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.SetJobPriorityResponse")
    public void setJobPriority(
        @WebParam(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        String uuid,
        @WebParam(name = "priority", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        int priority)
        throws TranscodeWSException_Exception
    ;

    /**
     * 
     * @param endOfExecutionDate
     * @param submissionDate
     * @return
     *     returns java.util.List<com.amberfin.ws.dark._2014._07.transcode.JobDetails>
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @WebResult(name = "job", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
    @RequestWrapper(localName = "getJobDetailsFromDate", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobDetailsFromDate")
    @ResponseWrapper(localName = "getJobDetailsFromDateResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobDetailsFromDateResponse")
    public List<JobDetails> getJobDetailsFromDate(
        @WebParam(name = "submissionDate", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        JobDate submissionDate,
        @WebParam(name = "endOfExecutionDate", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        JobDate endOfExecutionDate)
        throws TranscodeWSException_Exception
    ;

    /**
     * 
     * @param replyParameters
     * @param transcodeparameters
     * @return
     *     returns java.lang.String
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @WebResult(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
    @RequestWrapper(localName = "addJob", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.AddJob")
    @ResponseWrapper(localName = "addJobResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.AddJobResponse")
    public String addJob(
        @WebParam(name = "transcodeparameters", targetNamespace = "http://www.amberfin.com/schema/TranscoderParameters")
        Transcodeparameters transcodeparameters,
        @WebParam(name = "replyParameters", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        JobReplyParameters replyParameters)
        throws TranscodeWSException_Exception
    ;

    /**
     * 
     * @param uuid
     * @return
     *     returns java.util.List<com.amberfin.ws.dark._2014._07.transcode.JobDetails>
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @WebResult(name = "job", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
    @RequestWrapper(localName = "getJobDetailsById", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobDetailsById")
    @ResponseWrapper(localName = "getJobDetailsByIdResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobDetailsByIdResponse")
    public List<JobDetails> getJobDetailsById(
        @WebParam(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        List<String> uuid)
        throws TranscodeWSException_Exception
    ;

    /**
     * 
     * @param uuid
     * @return
     *     returns int
     * @throws TranscodeWSException_Exception
     */
    @WebMethod
    @WebResult(name = "progress", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
    @RequestWrapper(localName = "getJobProgress", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobProgress")
    @ResponseWrapper(localName = "getJobProgressResponse", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", className = "com.amberfin.ws.dark._2014._07.transcode.GetJobProgressResponse")
    public int getJobProgress(
        @WebParam(name = "uuid", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode")
        String uuid)
        throws TranscodeWSException_Exception
    ;

}
