
package com.amberfin.ws.dark._2014._07.transcode;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TranscodeWSService", targetNamespace = "http://amberfin.com/ws/dark/2014/07/Transcode", wsdlLocation = "file:/D:/src/AmberFin/amberfin-soap-api-Transcode.wsdl")
public class TranscodeWSService
    extends Service
{

    private final static URL TRANSCODEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSCODEWSSERVICE_EXCEPTION;
    private final static QName TRANSCODEWSSERVICE_QNAME = new QName("http://amberfin.com/ws/dark/2014/07/Transcode", "TranscodeWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/src/AmberFin/amberfin-soap-api-Transcode.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TRANSCODEWSSERVICE_WSDL_LOCATION = url;
        TRANSCODEWSSERVICE_EXCEPTION = e;
    }

    public TranscodeWSService() {
        super(__getWsdlLocation(), TRANSCODEWSSERVICE_QNAME);
    }

    public TranscodeWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSCODEWSSERVICE_QNAME, features);
    }

    public TranscodeWSService(URL wsdlLocation) {
        super(wsdlLocation, TRANSCODEWSSERVICE_QNAME);
    }

    public TranscodeWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSCODEWSSERVICE_QNAME, features);
    }

    public TranscodeWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TranscodeWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TranscodeWS
     */
    @WebEndpoint(name = "TranscodeWSPort")
    public TranscodeWS getTranscodeWSPort() {
        return super.getPort(new QName("http://amberfin.com/ws/dark/2014/07/Transcode", "TranscodeWSPort"), TranscodeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TranscodeWS
     */
    @WebEndpoint(name = "TranscodeWSPort")
    public TranscodeWS getTranscodeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://amberfin.com/ws/dark/2014/07/Transcode", "TranscodeWSPort"), TranscodeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSCODEWSSERVICE_EXCEPTION!= null) {
            throw TRANSCODEWSSERVICE_EXCEPTION;
        }
        return TRANSCODEWSSERVICE_WSDL_LOCATION;
    }

}
